---
title: "Stacked Bar Plots - tumor"
output: html_document
date: '2022-07-10'

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
library(RColorBrewer)
library(ggplot2)
library(grid)
library(MASS)
library("pheatmap")
library(viridis)
library(reshape2)
library(readxl)
```

```{r}

#setwd per user

files  = c("jhmi-esca-microbiota.genus.xlsx")

GroupCols = c("#e4e4e4", "#eb3eab", "#FF9AA2", "#FFDAC1", "#E2F0CB", "#B5EAD7", "#C7CEEA", "#8e7cc3", "#f94144","#f8961e","#f9b14a","#f9c74f","#90be6d","#82d3d1","#4d908e","#6ec2e5","#277da1")
numTx     = 19
GroupCols = colorRampPalette(GroupCols)(numTx+1)

pdf(file= "Stacked bar plots.pdf" )

for(f in files){
  A <- read_excel(f)
  A$pathCR = paste0("PathCR ", as.character(A$pathCR))
  A        = A[A$pathCR != "n/a",]
  A$pathCR = factor(A$pathCR, levels=c("PathCR 0", "PathCR 1"))
  colnames(A) = gsub("k_Bacteria.","",colnames(A))
  A  <- subset(A, SampleType %in% c("Tissue_tumor"))

  if (grepl("genus",f)){
    colnames(A) = gsub("p_Firmicutes\\.|p_Actinobacteria\\.|p_Bacteroidetes\\.", "", colnames(A))
  }

  A = A[,c(6,25,34:ncol(A))]
  aggA            = aggregate( . ~ RecordID + pathCR, data=A, FUN=mean)
  cmaggA          = colMeans(aggA[3:ncol(aggA)])
  selectedA       = names(cmaggA[order(cmaggA, decreasing=TRUE)])[1:min(numTx,length(cmaggA))]
  aggA            = aggA[,c("RecordID", "pathCR", selectedA)]
  aggA$Other.taxa = 100-rowSums(aggA[3:ncol(aggA)])

  meltA           = melt(aggA, id.vars = c("RecordID", "pathCR"))
  colnames(meltA) = c("RecordID", "pathCR", "Taxa", "Abundance")

  meltA$pathCR    = factor(meltA$pathCR)

  meltA$Taxa      = factor(meltA$Taxa, levels=rev(levels(meltA$Taxa)))

  customOrder     = aggA[order(rowSums(aggA[,selectedA[1:2]]), decreasing=TRUE),"RecordID"]

  meltA$RecordID  = factor(meltA$RecordID, levels=customOrder)
  
  p1 <- ggplot(meltA, aes(x=RecordID, y=Abundance, fill=Taxa))  +
  geom_bar(position="stack", stat="identity", colour="white", linewidth=0.25) +
  theme_bw() +
  scale_fill_manual(values=GroupCols) +
  theme(axis.text.x = element_text(size =6, colour="black", angle=45, hjust=1, vjust=1),
        axis.text.y = element_text(size=10, colour="black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title       = element_text(size=10, colour="black"),
        legend.text      = element_text(size=5),
        legend.title     = element_blank()) +
  xlab(NULL) +
  ylab("% Abundance") +
  facet_grid(~pathCR, space="free_x", scale="free_x") +
  ggtitle("Tumor pathCR")
  plot(p1)
}

p1

ggsave(paste("Figure-3A-tumor-stacked-bar-plot.pdf",sep=""), p1)


```




